name: pillowtalk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.0
  go_router: ^16.0.0
  permission_handler: ^12.0.1
  awesome_notifications: ^0.10.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/logo.png
  android_12:
    image: assets/logo/logo.png
    color: "#ffffff"

# app icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 21

  

  