name: pillow_talk
description: "A couple Well Being app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  awesome_notifications: ^0.10.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.0
  go_router: ^16.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/
    - assets/icons/

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/web-app-manifest-512x512.png
  android_12:
    image: assets/logo/web-app-manifest-512x512.png
    color: "#ffffff"

# app icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  
